######################################
##                                  ##
##          Hypr Autostart          ##
##                                  ##
######################################

exec-once = dbus-update-activation-environment --systemd DISPLAY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

exec-once = swaync
exec-once = hypridle
exec-once = swww init
exec-once = hyprsunset
exec-once = waypaper --restore

exec-once =  [workspace special] kitty --class kitty-dropterm
exec-once = [workspace 9 silent] kitty -e calcure
exec-once = [workspace 8 silent] kitty -e yazi
exec-once = [workspace 7 silent] kitty -e aerc
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

exec-once = waybar -c ~/.config/waybar/config -s ~/.config/waybar/style.css
exec-once = waybar -c ~/.config/waybar/config-bottom.jsonc -s ~/.config/waybar/style-bottom.css

exec = gsettings set org.gnome.desktop.interface gtk-theme 'Adwaita-dark'
exec = gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
exec = gsettings set org.gnome.desktop.interface icon-theme 'Tela-dracula-dark'
