######################################
##                                  ##
##            Hypr Input            ##
##                                  ##
######################################


# --- Input ---
input {
    kb_layout = fr
    touchpad {
        natural_scroll = true        # défilement naturel
        tap-to-click   = true        # tap pour cliquer
        scroll_factor  = 0.7         # vitesse de scroll (1 par défaut, <1 plus lent, >1 plus rapide)
    }
}
