######################################
##                                  ##
##           Hypr Rules             ##
##                                  ##
######################################

# Deezer
windowrule = workspace 10, match:class ^deezer-desktop$

# Kitty
windowrule = float on, match:class ^kitty-dropterm$
windowrule = center on, match:class ^kitty-dropterm$
windowrule = workspace special, match:class ^kitty-dropterm$
windowrule = size 800 800, match:class ^kitty-dropterm$
windowrule = opacity 0.8, match:class ^kitty$

# Blueman-mannager
windowrule = float on, match:class ^blueman-manager$
windowrule = size 450 450, match:class ^blueman-manager$

# Waypaper
windowrule = float on, match:class ^waypaper$
windowrule = size 600 600, match:class ^waypaper$

