######################################
##                                  ##
##            Hypr Theme            ##
##                                  ##
######################################

misc {
    force_default_wallpaper = 0
    disable_hyprland_logo = true
    background_color = 0x111111
}

general {
    gaps_in = 3
    gaps_out = 10
    border_size = 1
    col.active_border = rgba(bb9af7ff) rgba(b4f9f8ff) 45deg
    col.inactive_border = rgba(565f89cc) rgba(9aa5cecc) 45deg
    layout = master
    resize_on_border = true
}

group {
    col.border_active = rgba(bb9af7ff) rgba(b4f9f8ff) 45deg
    col.border_inactive = rgba(565f89cc) rgba(9aa5cecc) 45deg
    col.border_locked_active = rgba(bb9af7ff) rgba(b4f9f8ff) 45deg
    col.border_locked_inactive = rgba(565f89cc) rgba(9aa5cecc) 45deg
}

decoration {
    rounding = 5
    active_opacity = 0.95
    inactive_opacity = 0.80
    fullscreen_opacity = 1.0

    blur {
        enabled = true
        size = 7
        passes = 2
        new_optimizations = true
        ignore_opacity = true  # pour garder un blur fort même si tu baisses l’opacité
    }
}

