max-gamma = 150

profile {
    time = 06:00
    identity = true      # pas de filtre, gamma normal
    gamma = 1.0
}

profile {
    time = 18:00
    temperature = 5500   # légèrement chaud
    gamma = 0.9
}

profile {
    time = 21:00
    temperature = 3500   # très chaud
    gamma = 0.8
}

